CREATE UNIQUE INDEX INF_B_DA_MNTH_MCO_CLMTYP_PK ON INF_B_DA_MNTH_MCO_CLMTYP
(DQ_BATCH_SEQ, CDE_ENC_MCO, SERVICE_MNTH, CDE_CLM_TYPE);

ALTER TABLE INF_B_DA_MNTH_MCO_CLMTYP ADD (
  CONSTRAINT INF_B_DA_MNTH_MCO_CLMTYP_PK
  PRIMARY KEY
  (DQ_BATCH_SEQ, CDE_ENC_MCO, SERVICE_MNTH, CDE_CLM_TYPE)
  USING INDEX INF_B_DA_MNTH_MCO_CLMTYP_PK
  ENABLE VALIDATE);

CREATE UNIQUE INDEX INF_B_DA_MNTH_MCO_ACO_CLMTYP_PK ON INF_B_DA_MNTH_MCO_ACO_CLMTYP
(DQ_BATCH_SEQ, ACO, SERVICE_MNTH, CDE_CLM_TYPE, CDE_ENC_MCO);

ALTER TABLE INF_B_DA_MNTH_MCO_ACO_CLMTYP ADD (
  CONSTRAINT INF_B_DA_MNTH_MCO_ACO_CLMTYP_PK
  PRIMARY KEY
  (DQ_BATCH_SEQ, ACO, SERVICE_MNTH, CDE_CLM_TYPE, CDE_ENC_MCO)
  USING INDEX INF_B_DA_MNTH_MCO_ACO_CLMTYP_PK
  ENABLE VALIDATE);

CREATE UNIQUE INDEX INF_B_DA_MNTH_CLMNUM_MCO_CLMTYP_PK ON INF_B_DA_MNTH_CLMNUM_MCO_CLMTYP
(DQ_BATCH_SEQ, CDE_ENC_MCO, SERVICE_MNTH, CDE_CLM_TYPE);

ALTER TABLE INF_B_DA_MNTH_CLMNUM_MCO_CLMTYP ADD (
  CONSTRAINT INF_B_DA_MNTH_CLMNUM_MCO_CLMTYP_PK
  PRIMARY KEY
  (DQ_BATCH_SEQ, CDE_ENC_MCO, SERVICE_MNTH, CDE_CLM_TYPE)
  USING INDEX INF_B_DA_MNTH_CLMNUM_MCO_CLMTYP_PK
  ENABLE VALIDATE);

CREATE UNIQUE INDEX INF_B_DA_MNTH_CLMNUM_MCO_ACO_CLMTYP_PK ON INF_B_DA_MNTH_CLMNUM_MCO_ACO_CLMTYP
(DQ_BATCH_SEQ, ACO, SERVICE_MNTH, CDE_CLM_TYPE, CDE_ENC_MCO);

ALTER TABLE INF_B_DA_MNTH_CLMNUM_MCO_ACO_CLMTYP ADD (
  CONSTRAINT INF_B_DA_MNTH_CLMNUM_MCO_ACO_CLMTYP_PK
  PRIMARY KEY
  (DQ_BATCH_SEQ, ACO, SERVICE_MNTH, CDE_CLM_TYPE, CDE_ENC_MCO)
  USING INDEX INF_B_DA_MNTH_CLMNUM_MCO_ACO_CLMTYP_PK
  ENABLE VALIDATE);

CREATE UNIQUE INDEX INF_B_DA_MNTH_UTIL_MEM_MCO_CLMTYP_PK ON INF_B_DA_MNTH_UTIL_MEM_MCO_CLMTYP
(DQ_BATCH_SEQ, CDE_ENC_MCO, SERVICE_MNTH, CDE_CLM_TYPE);

ALTER TABLE INF_B_DA_MNTH_UTIL_MEM_MCO_CLMTYP ADD (
  CONSTRAINT INF_B_DA_MNTH_UTIL_MEM_MCO_CLMTYP_PK
  PRIMARY KEY
  (DQ_BATCH_SEQ, CDE_ENC_MCO, SERVICE_MNTH, CDE_CLM_TYPE)
  USING INDEX INF_B_DA_MNTH_UTIL_MEM_MCO_CLMTYP_PK
  ENABLE VALIDATE);

CREATE UNIQUE INDEX INF_B_DA_MNTH_UTIL_MEM_MCO_ACO_CLMTYP_PK ON INF_B_DA_MNTH_UTIL_MEM_MCO_ACO_CLMTYP
(DQ_BATCH_SEQ, ACO, SERVICE_MNTH, CDE_CLM_TYPE, CDE_ENC_MCO);

ALTER TABLE INF_B_DA_MNTH_UTIL_MEM_MCO_ACO_CLMTYP ADD (
  CONSTRAINT INF_B_DA_MNTH_UTIL_MEM_MCO_ACO_CLMTYP_PK
  PRIMARY KEY
  (DQ_BATCH_SEQ, ACO, SERVICE_MNTH, CDE_CLM_TYPE, CDE_ENC_MCO)
  USING INDEX INF_B_DA_MNTH_UTIL_MEM_MCO_ACO_CLMTYP_PK
  ENABLE VALIDATE);

CREATE UNIQUE INDEX INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_A_PK ON INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_A
(DQ_BATCH_SEQ, CDE_ENC_MCO, CDE_CLM_TYPE, SERVICE_MNTH);

ALTER TABLE INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_A ADD (
  CONSTRAINT INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_A_PK
  PRIMARY KEY
(DQ_BATCH_SEQ, CDE_ENC_MCO, CDE_CLM_TYPE, SERVICE_MNTH)
  USING INDEX INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_A_PK
  ENABLE VALIDATE);

CREATE UNIQUE INDEX INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_B_PK ON INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_B
(DQ_BATCH_SEQ, CDE_ENC_MCO, CDE_CLM_TYPE, SERVICE_MNTH);

ALTER TABLE INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_B ADD (
  CONSTRAINT INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_B_PK
  PRIMARY KEY
(DQ_BATCH_SEQ, CDE_ENC_MCO, CDE_CLM_TYPE, SERVICE_MNTH)
  USING INDEX INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_B_PK
  ENABLE VALIDATE);

CREATE UNIQUE INDEX INF_B_DA_MNTH_MCO_ACO_BASE_PK ON INF_B_DA_MNTH_MCO_ACO_BASE
(DQ_BATCH_SEQ, ACO, SERVICE_MNTH, CDE_CLM_TYPE, CDE_ENC_MCO, ENC_CLAIM_NO, ENC_CLAIM_SUFFIX);

ALTER TABLE INF_B_DA_MNTH_MCO_ACO_BASE ADD (
  CONSTRAINT INF_B_DA_MNTH_MCO_ACO_BASE_PK
  PRIMARY KEY
(DQ_BATCH_SEQ, ACO, SERVICE_MNTH, CDE_CLM_TYPE, CDE_ENC_MCO, ENC_CLAIM_NO, ENC_CLAIM_SUFFIX)
  USING INDEX INF_B_DA_MNTH_MCO_ACO_BASE_PK
  ENABLE VALIDATE);

CREATE UNIQUE INDEX INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE_PK ON INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE
(DQ_BATCH_SEQ, ACO, SERVICE_MNTH, CDE_CLM_TYPE, CDE_ENC_MCO, ENC_CLAIM_NO, ENC_CLAIM_SUFFIX);

ALTER TABLE INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE ADD (
  CONSTRAINT INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE_PK
  PRIMARY KEY
(DQ_BATCH_SEQ, ACO, SERVICE_MNTH, CDE_CLM_TYPE, CDE_ENC_MCO, ENC_CLAIM_NO, ENC_CLAIM_SUFFIX)
  USING INDEX INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE_PK
  ENABLE VALIDATE);

