--select 'GRANT SELECT ON ' || table_name || ' TO nw_read;' from user_tables
--order by table_name

GRANT SELECT ON INF_B_DA_MNTH_CLMNUM_MCO_ACO_CLMTYP TO nw_read;
GRANT SELECT ON INF_B_DA_MNTH_CLMNUM_MCO_CLMTYP TO nw_read;
GRANT SELECT ON INF_B_DA_MNTH_MCO_ACO_BASE TO nw_read;
GRANT SELECT ON INF_B_DA_MNTH_MCO_ACO_CLMTYP TO nw_read;
GRANT SELECT ON INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE TO nw_read;
GRANT SELECT ON INF_B_DA_MNTH_MCO_CLMTYP TO nw_read;
GRANT SELECT ON INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_A TO nw_read;
GRANT SELECT ON INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_B TO nw_read;
GRANT SELECT ON INF_B_DA_MNTH_UTIL_MEM_MCO_ACO_CLMTYP TO nw_read;
GRANT SELECT ON INF_B_DA_MNTH_UTIL_MEM_MCO_CLMTYP TO nw_read;
GRANT SELECT ON INF_B_DQ_LOAD_BATCH TO nw_read;
GRANT SELECT ON INF_B_DQ_PARAMS TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_ALL_CLAIM_TYPES TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_ALL_CLAIM_TYPES_2 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_ALL_CLAIM_TYPES_PCT TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_ALL_CLAIM_TYPES_PCT_2 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_MBHP_DOS_MAR2018_JUN2018 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_MBH_FLDREX_MAR2018_JUN2018 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_MBH_FRDOS_MAR2018_JUN2018 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_MBH_FRPDOS_MAR2018_JUN2018 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_MBH_PCNT_MAR2018_JUN2018 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_MBH_PCTDOS_MAR2018_JUN2018 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_MBH_PTPDOS_MAR2018_JUN2018 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_MBH_REP_STEP1_MAR2018_JUN2018 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_MBH_REP_STEP2_MAR2018_JUN2018 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_MBH_REP_TRANSPOSE_MAR2018_JUN2018 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_MBH_TDOS_MAR2018_JUN2018 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_MBH_TOTREX_MAR2018_JUN2018 TO nw_read;
GRANT SELECT ON INF_B_SC_MCO_MBH_TPDOS_MAR2018_JUN2018 TO nw_read;
GRANT SELECT ON INF_B_SC_STG_MCO_ALL_CLAIM_TYPES TO nw_read;

--select 'GRANT SELECT ON ' || view_name || ' TO nw_read;' from user_views
--order by view_name

GRANT SELECT ON INF_DA_MNTH_CLMNUM_MCO_ACO_CLMTYP TO nw_read;
GRANT SELECT ON INF_DA_MNTH_CLMNUM_MCO_CLMTYP TO nw_read;
GRANT SELECT ON INF_DA_MNTH_MCO_ACO_BASE TO nw_read;
GRANT SELECT ON INF_DA_MNTH_MCO_ACO_CLMTYP TO nw_read;
GRANT SELECT ON INF_DA_MNTH_MCO_ACO_REVCDE_BASE TO nw_read;
GRANT SELECT ON INF_DA_MNTH_MCO_CLMTYP TO nw_read;
GRANT SELECT ON INF_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_A TO nw_read;
GRANT SELECT ON INF_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_B TO nw_read;
GRANT SELECT ON INF_DA_MNTH_UTIL_MEM_MCO_ACO_CLMTYP TO nw_read;
GRANT SELECT ON INF_DA_MNTH_UTIL_MEM_MCO_CLMTYP TO nw_read;
