
CREATE OR REPLACE VIEW INF_DA_MNTH_MCO_CLMTYP
AS
SELECT 
  RUN_DATE,
  DQ_BATCH_SEQ,
  CDE_ENC_MCO,
  CDE_CLM_TYPE,
  SERVICE_MNTH,
  TOTAL_DISTINCT_CLAIMS,
  TOTAL_UTILIZING_MEMBERS,
  TOTAL_PD,
  AVG_TOTAL_PD,
  MIN_TOTAL_PD,
  MAX_TOTAL_PD,
  STDEV_TOTAL_PD,
  MED_TOTAL_PD,
  TOTAL_REC,
  TOTAL_PD_12_MNTH_RLNG_SUM,
  AVG_PD_12_MNTH_RLNG_AVG,
  AVG_PD_12_MNTH_RLNG_STDEV,
  MED_PD_12_MNTH_RLNG_AVG
FROM INF_B_DA_MNTH_MCO_CLMTYP;

CREATE OR REPLACE VIEW INF_DA_MNTH_MCO_ACO_CLMTYP
AS
SELECT
  RUN_DATE,
  DQ_BATCH_SEQ,
  CDE_ENC_MCO,
  ACO,
  CDE_CLM_TYPE,
  SERVICE_MNTH,
  TOTAL_DISTINCT_CLAIMS,
  TOTAL_UTILIZING_MEMBERS,
  TOTAL_PD,
  AVG_TOTAL_PD,
  MIN_TOTAL_PD,
  MAX_TOTAL_PD,
  STDEV_TOTAL_PD,
  MED_TOTAL_PD,
  TOTAL_REC,
  TOTAL_PD_12_MNTH_RLNG_SUM,
  AVG_PD_12_MNTH_RLNG_AVG,
  AVG_PD_12_MNTH_RLNG_STDEV,
  MED_PD_12_MNTH_RLNG_AVG
FROM INF_B_DA_MNTH_MCO_ACO_CLMTYP;

CREATE OR REPLACE VIEW INF_DA_MNTH_CLMNUM_MCO_CLMTYP
AS
SELECT
  RUN_DATE,
  DQ_BATCH_SEQ,
  CDE_ENC_MCO,
  CDE_CLM_TYPE,
  SERVICE_MNTH,
  TOTAL_DISTINCT_CLAIMS,
  TOTAL_PD,
  AVG_TOTAL_PD,
  MIN_TOTAL_PD,
  MAX_TOTAL_PD,
  STDEV_TOTAL_PD,
  MED_TOTAL_PD,
  TOTAL_REC,
  AVG_REC,
  MIN_REC,
  MAX_REC,
  STDEV_REC,
  MED_REC,
  TOTAL_PD_12_MNTH_RLNG_SUM,
  AVG_PD_12_MNTH_RLNG_AVG,
  AVG_PD_12_MNTH_RLNG_STDEV,
  MED_PD_12_MNTH_RLNG_AVG,
  TOTAL_REC_12_MNTH_RLNG_SUM,
  AVG_REC_12_MNTH_RLNG_AVG,
  AVG_REC_12_MNTH_RLNG_STDEV,
  MED_REC_12_MNTH_RLNG_AVG
FROM INF_B_DA_MNTH_CLMNUM_MCO_CLMTYP;

CREATE OR REPLACE VIEW INF_DA_MNTH_CLMNUM_MCO_ACO_CLMTYP
AS
SELECT
  RUN_DATE,
  DQ_BATCH_SEQ,
  CDE_ENC_MCO,
  ACO,
  CDE_CLM_TYPE,
  SERVICE_MNTH,
  TOTAL_DISTINCT_CLAIMS,
  TOTAL_PD,
  AVG_TOTAL_PD,
  MIN_TOTAL_PD,
  MAX_TOTAL_PD,
  STDEV_TOTAL_PD,
  MED_TOTAL_PD,
  TOTAL_REC,
  AVG_REC,
  MIN_REC,
  MAX_REC,
  STDEV_REC,
  MED_REC,
  TOTAL_PD_12_MNTH_RLNG_SUM,
  AVG_PD_12_MNTH_RLNG_AVG,
  AVG_PD_12_MNTH_RLNG_STDEV,
  MED_PD_12_MNTH_RLNG_AVG,
  TOTAL_REC_12_MNTH_RLNG_SUM,
  AVG_REC_12_MNTH_RLNG_AVG,
  AVG_REC_12_MNTH_RLNG_STDEV,
  MED_REC_12_MNTH_RLNG_AVG
FROM INF_B_DA_MNTH_CLMNUM_MCO_ACO_CLMTYP;

CREATE OR REPLACE VIEW INF_DA_MNTH_UTIL_MEM_MCO_CLMTYP
AS 
SELECT 
  RUN_DATE,
  DQ_BATCH_SEQ,
  CDE_ENC_MCO,
  CDE_CLM_TYPE,
  SERVICE_MNTH,
  TOTAL_DISTINCT_CLAIMS,
  TOTAL_UTILIZING_MEMBERS,
  TOTAL_PAID,
  AVG_TOTAL_PD,
  MIN_TOTAL_PD,
  MAX_TOTAL_PD,
  STDEV_TOTAL_PD,
  MEDIAN_TOTAL_PD,
  TOTAL_REC,
  AVG_REC,
  MIN_REC,
  MAX_REC,
  STDEV_REC,
  MEDIAN_REC,
  TOTAL_PD_12_MNTH_RLNG_SUM,
  AVG_PD_12_MNTH_RLNG_AVG,
  AVG_PD_12_MNTH_RLNG_STDEV,
  MED_PD_12_MNTH_RLNG_AVG,
  TOTAL_REC_12_MNTH_RLNG_SUM,
  AVG_REC_12_MNTH_RLNG_AVG,
  AVG_REC_12_MNTH_RLNG_STDEV,
  MED_REC_12_MNTH_RLNG_AVG
FROM INF_B_DA_MNTH_UTIL_MEM_MCO_CLMTYP;

CREATE OR REPLACE VIEW INF_DA_MNTH_UTIL_MEM_MCO_ACO_CLMTYP
AS 
SELECT 
  RUN_DATE,
  DQ_BATCH_SEQ,
  CDE_ENC_MCO,
  ACO,
  CDE_CLM_TYPE,
  SERVICE_MNTH,
  TOTAL_DISTINCT_CLAIMS,
  TOTAL_UTILIZING_MEMBERS,
  TOTAL_PD,
  AVG_TOTAL_PD,
  MIN_TOTAL_PD,
  MAX_TOTAL_PD,
  STDEV_TOTAL_PD,
  MED_TOTAL_PD,
  TOTAL_REC,
  AVG_REC,
  MIN_REC,
  MAX_REC,
  STDEV_REC,
  MED_REC,
  TOTAL_PD_12_MNTH_RLNG_SUM,
  AVG_PD_12_MNTH_RLNG_AVG,
  AVG_PD_12_MNTH_RLNG_STDEV,
  MED_PD_12_MNTH_RLNG_AVG,
  TOTAL_REC_12_MNTH_RLNG_SUM,
  AVG_REC_12_MNTH_RLNG_AVG,
  AVG_REC_12_MNTH_RLNG_STDEV,
  MED_REC_12_MNTH_RLNG_AVG
FROM INF_B_DA_MNTH_UTIL_MEM_MCO_ACO_CLMTYP;

CREATE OR REPLACE VIEW INF_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_A
AS
SELECT
  RUN_DATE,
  DQ_BATCH_SEQ,
  CDE_ENC_MCO,
  CDE_CLM_TYPE,
  SERVICE_MNTH,
  TOTAL_REC,
  TOTAL_DISTINCT_CLAIMS,
  TOTAL_REVCDE,
  DIFF_TOTAL_REC_TOTAL_REVCDE,
  AVG_REC_PER_CLAIM,
  AVG_REVCDE_PER_CLAIM,
  AVG_RATIO_REC_TO_REVCDE,
  MIN_RATIO_REC_TO_REVCDE,
  MAX_RATIO_REC_TO_REVCDE,
  STDDEV_RATIO_REC_TO_REVCDE,
  MEDIAN_RATIO_REC_TO_REVCDE
FROM INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_A;

CREATE OR REPLACE VIEW INF_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_B
AS
SELECT
  RUN_DATE,
  DQ_BATCH_SEQ,
  CDE_ENC_MCO,
  CDE_CLM_TYPE,
  SERVICE_MNTH,
  TOTAL_REC,
  TOTAL_DISTINCT_CLAIMS,
  TOTAL_REVCDE,
  DIFF_TOTAL_REC_TOTAL_REVCDE,
  AVG_REC_PER_CLAIM,
  AVG_REVCDE_PER_CLAIM,
  RATIO_AVG_REC_TO_REVCDE,
  MIN_RATIO_AVG_REC_TO_REVCDE,
  MAX_RATIO_AVG_REC_TO_REVCDE,
  STDDEV_RATIO_AVG_REC_TO_REVCDE,
  MED_RATIO_AVG_REC_TO_REVCDE
FROM INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_B;

CREATE OR REPLACE VIEW INF_DA_MNTH_MCO_ACO_BASE
AS
SELECT
  RUN_DATE,
  DQ_BATCH_SEQ,
  CDE_ENC_MCO,
  ACO,
  CDE_CLM_TYPE,
  SERVICE_MNTH,
  DOS_FROM_DT,
  DOS_TO_DT,
  REMIT_FROM_DT,
  REMIT_THRU_DT,
  ENC_CLAIM_NO,
  ENC_CLAIM_SUFFIX,
  AMT_PAID,
  AMT_BILLED,
  WH_FROM_DT,
  WH_THRU_DT,
  IND_OFFSET,
  CDE_CLM_DISPOSITION,
  MEM_SEQ,
  ID_MEDICAID_CRNT,
  ID_MEDICAID_VALID_FROM_DT_TM
FROM INF_B_DA_MNTH_MCO_ACO_BASE;

CREATE OR REPLACE VIEW INF_DA_MNTH_MCO_ACO_REVCDE_BASE
AS
SELECT
  RUN_DATE,
  DQ_BATCH_SEQ,
  CDE_ENC_MCO,
  ACO,
  SERVICE_MNTH,
  CDE_CLM_TYPE,
  DOS_FROM_DT,
  DOS_TO_DT,
  REMIT_FROM_DT,
  REMIT_THRU_DT,
  ENC_CLAIM_NO,
  ENC_CLAIM_SUFFIX,
  AMT_PAID,
  AMT_BILLED,
  ATTRSRV_SEQ,
  ATTRENC_SEQ,
  CDE_CLM_DISPOSITION,
  CDE_REVENUE,
  CDE_ENC_REC_IND
FROM INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE;





