GRANT SELECT ON INF_DA_MNTH_CLMNUM_MCO_ACO_CLMTYP_V1_9 TO nw_read;
/
GRANT SELECT ON INF_DA_MNTH_CLMNUM_MCO_CLMTYP_V1_9 TO nw_read;
/
GRANT SELECT ON INF_DA_MNTH_MCO_ACO_BASE TO nw_read;
/
GRANT SELECT ON INF_DA_MNTH_MCO_ACO_CLMTYP_V1_9 TO nw_read;
/
GRANT SELECT ON INF_DA_MNTH_MCO_ACO_REVCDE_BASE TO nw_read;
/
GRANT SELECT ON INF_DA_MNTH_MCO_CLMTYP_V1_9 TO nw_read;
/
GRANT SELECT ON INF_DA_MNTH_UTIL_MEM_MCO_ACO_CLMTYP_V1_9 TO nw_read;
/
GRANT SELECT ON INF_DA_MNTH_UTIL_MEM_MCO_CLMTYP_V1_9 TO nw_read;
/
EXIT
