SET pause OFF
SET feedback ON
SET TIME ON
SET timing ON


WHENEVER SQLERROR EXIT failure ROLLBACK

DECLARE 
    v_DA_PURCE_AGG     NUMBER(3);
    v_DA_PURCE_DTL     NUMBER(3);
    v_DA_RUN_DATE      DATE;
    v_PARENT_BATCH_SEQ NUMBER(10);
    v_CHILD_BATCH_SEQ  NUMBER(10);
    v_AGG_PURGE_DATE   DATE;
    v_DTL_PURGE_DATE   DATE;
    
BEGIN
 -- Subtract one month because we will be adding the latest month later
    SELECT - (TO_NUMBER(PARAM_VALUE, '999') - 1) INTO v_DA_PURCE_AGG     FROM INF_B_DQ_PARAMS WHERE PARAM_NAME = 'DA_PURGE_AGG';
    SELECT - (TO_NUMBER(PARAM_VALUE, '999') - 1) INTO v_DA_PURCE_DTL     FROM INF_B_DQ_PARAMS WHERE PARAM_NAME = 'DA_PURGE_DTL';
    SELECT TO_DATE(PARAM_VALUE,'YYYYMMDD')       INTO v_DA_RUN_DATE      FROM INF_B_DQ_PARAMS WHERE PARAM_NAME = 'DA_RUN_DATE';
    SELECT TO_NUMBER(PARAM_VALUE, '999999')      INTO v_PARENT_BATCH_SEQ FROM INF_B_DQ_PARAMS WHERE PARAM_NAME = 'DA_BATCH_SEQ';

    SELECT ADD_MONTHS(TRUNC(v_DA_RUN_DATE,'MONTH'),v_DA_PURCE_AGG) INTO v_AGG_PURGE_DATE FROM DUAL;
    SELECT ADD_MONTHS(TRUNC(v_DA_RUN_DATE,'MONTH'),v_DA_PURCE_DTL) INTO v_DTL_PURGE_DATE FROM DUAL;
       
    --DBMS_OUTPUT.PUT_LINE('v_AGG_PURGE_DATE ' || to_char(v_AGG_PURGE_DATE,'YYYYMMDD'));
    --DBMS_OUTPUT.PUT_LINE('v_DTL_PURGE_DATE ' || to_char(v_DTL_PURGE_DATE,'YYYYMMDD'));
    
    --Put an entry in INF_B_DQ_LOAD_BATCH so the main script can wait for this script to finish
    
    INSERT INTO INF_B_DQ_LOAD_BATCH
    (
        RUN_DATE,
        STEP_NUM,
        PROJECT_NAME,
        PROGRAM_NAME,
        PARENT_BATCH_SEQ,
        BATCH_START_DT_TM,
        STATUS
    )
    VALUES
    (
        v_DA_RUN_DATE,
        7,
        'DA',
        'PURGE_TABLES',
        v_PARENT_BATCH_SEQ,
        SYSDATE,
        'Running'
    )
    RETURNING DQ_BATCH_SEQ INTO v_CHILD_BATCH_SEQ;
    

    DELETE FROM INF_B_DA_MNTH_MCO_CLMTYP_V1_9 WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_MCO_ACO_CLMTYP_V1_9 WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_CLMNUM_MCO_CLMTYP_V1_9 WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_CLMNUM_MCO_ACO_CLMTYP_V1_9 WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_UTIL_MEM_MCO_CLMTYP_V1_9 WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_UTIL_MEM_MCO_ACO_CLMTYP_V1_9 WHERE RUN_DATE < v_AGG_PURGE_DATE;

-- I am using truncate copies - it is cleaner, but more dangerous
--    DELETE FROM INF_B_DA_MNTH_MCO_ACO_BASE WHERE RUN_DATE < v_DTL_PURGE_DATE;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_BASE_purge';
    INSERT INTO INF_B_DA_MNTH_MCO_ACO_BASE_purge SELECT * FROM INF_B_DA_MNTH_MCO_ACO_BASE WHERE RUN_DATE > v_DTL_PURGE_DATE;
    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_BASE REUSE STORAGE';
    INSERT INTO INF_B_DA_MNTH_MCO_ACO_BASE SELECT * FROM INF_B_DA_MNTH_MCO_ACO_BASE_purge;
    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_BASE_purge';

--    DELETE FROM INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE WHERE RUN_DATE < v_DTL_PURGE_DATE;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE_purge';
    INSERT INTO INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE_purge SELECT * FROM INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE WHERE RUN_DATE > v_DTL_PURGE_DATE;
    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE REUSE STORAGE';
    INSERT INTO INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE SELECT * FROM INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE_purge;
    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE_purge';

    UPDATE INF_B_DQ_LOAD_BATCH
    SET BATCH_END_DT_TM = SYSDATE,
    STATUS              = 'Complete'
    WHERE DQ_BATCH_SEQ  = v_CHILD_BATCH_SEQ;

    COMMIT;
        
END;
/

