SET pause OFF
SET echo ON
SET feedback ON
SET TIME ON
SET timing ON

whenever sqlerror exit failure rollback

DROP TABLE INF_B_DQ_PARAMS CASCADE CONSTRAINTS;
/
CREATE TABLE INF_B_DQ_PARAMS
(
  PARAM_NAME   VARCHAR2(40 BYTE)                NOT NULL,
  PARAM_VALUE  VARCHAR2(255 BYTE)               NOT NULL,
  PARAM_DESC   VARCHAR2(255 BYTE)
)
/
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
'SC_RUN_DATE', 'NOT SET', 'LATEST SCORECARD RUN DATE as YYYYMMDD also used as ASOFDT');
/
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
'SC_BATCH_SEQ', 'NOT SET', 'LATEST PARENT (BASH) SCORECARD DQ_BATCH_SEQ');
/
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
'SC_MIN_DOS', 'NOT SET', 'LATEST SCORECARD START DATE OF SERVICE as YYYYMMDD also used as MONS');
/
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
'SC_MAX_DOS', 'NOT SET', 'LATEST SCORECARD END DATE OF SERVICE as YYYYMMDD');
/
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
'SC_MON', 'NOT SET', 'LATEST SCORECARD CONCATENATED START AND END DATE as MONYYYY_MONYYYY');
/
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
'DA_RUN_DATE', 'NOT SET', 'LATEST ANOMALY RUN DATE - YYYYMMDD');
/
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
'DA_BATCH_SEQ', 'NOT SET', 'LATEST PARENT (BASH) ANOMALY DQ_BATCH_SEQ');
/
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
'DA_MIN_DOS', 'NOT SET', 'LATEST ANOMALY START DATE OF SERVICE as YYYYMMDD');
/
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
'DA_MAX_DOS', 'NOT SET', 'LATEST ANOMALY END DATE OF SERVICE as YYYYMMDD');
/
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
'DA_PURGE_DTL', '3', 'NUMBER OF MONTHS TO RETAIN IN DETAIL TABLES');
/
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
'DA_PURGE_AGG', '24', 'NUMBER OF MONTHS TO RETAIN IN AGGREGATION TABLES');
/
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
'DA_PULL_END_MNTHS_BACK', '3', 'NUMBER OF MONTHS BACK TO END PULL');
/
--Switching to using Years vs 36 months because Viz uses full years
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
'DA_PULL_START_YRS_BACK', '3', 'NUMBER OF YEARS BACK TO START PULL');
/
--INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
--'DA_REVIEW_MNTHS', '24', 'NUMBER OF MONTHS REVIEWED IN EACH SNAPSHOT');
/
--INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (
--'DA_ROLL_WIN_MNTHS', '12', 'NUMBER OF MONTHS IN ROLLING WINDOWS');
/
INSERT INTO INF_B_DQ_PARAMS ( PARAM_NAME, PARAM_VALUE, PARAM_DESC ) VALUES (                                         'SC_RUN_DATE_TO_MAX_OFFSET_MNTHS', '5', 'NUMBER OF MONTHS BETWEEN RUN DATE AND MAX DOS');
/
COMMIT;
/

EXIT

