DECLARE 
    v_DA_PURCE_AGG   NUMBER(3);
    v_DA_PURCE_DTL   NUMBER(3);
    v_DA_RUN_DATE    VARCHAR2(8);
    v_AGG_PURGE_DATE DATE;
    v_DTL_PURGE_DATE DATE;
    
BEGIN
 -- Subtract one month because we will be adding the latest month later
    SELECT - (TO_NUMBER(PARAM_VALUE, '999') - 1) INTO v_DA_PURCE_AGG FROM INF_B_DQ_PARAMS WHERE PARAM_NAME = 'DA_PURGE_AGG';
    SELECT - (TO_NUMBER(PARAM_VALUE, '999') - 1) INTO v_DA_PURCE_DTL FROM INF_B_DQ_PARAMS WHERE PARAM_NAME = 'DA_PURGE_DTL';
    SELECT PARAM_VALUE                         INTO v_DA_RUN_DATE  FROM INF_B_DQ_PARAMS WHERE PARAM_NAME = 'DA_RUN_DATE';

    SELECT ADD_MONTHS(TRUNC(to_date(v_DA_RUN_DATE,'YYYYMMDD'),'MONTH'),v_DA_PURCE_AGG) INTO v_AGG_PURGE_DATE FROM DUAL;
    SELECT ADD_MONTHS(TRUNC(to_date(v_DA_RUN_DATE,'YYYYMMDD'),'MONTH'),v_DA_PURCE_DTL) INTO v_DTL_PURGE_DATE FROM DUAL;
    
    DBMS_OUTPUT.PUT_LINE('v_AGG_PURGE_DATE ' || to_char(v_AGG_PURGE_DATE,'YYYYMMDD'));
    DBMS_OUTPUT.PUT_LINE('v_DTL_PURGE_DATE ' || to_char(v_DTL_PURGE_DATE,'YYYYMMDD'));
    
    DELETE FROM INF_B_DA_MNTH_MCO_CLMTYP WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_MCO_ACO_CLMTYP WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_CLMNUM_MCO_CLMTYP WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_CLMNUM_MCO_ACO_CLMTYP WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_UTIL_MEM_MCO_CLMTYP WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_UTIL_MEM_MCO_ACO_CLMTYP WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_A WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_REVCDE_CLMNUM_MCO_CLMTYP_B WHERE RUN_DATE < v_AGG_PURGE_DATE;

-- I am using truncate copies - it is cleaner, but more dangerous
--    DELETE FROM INF_B_DA_MNTH_MCO_ACO_BASE WHERE RUN_DATE < v_DTL_PURGE_DATE;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_BASE_purge';
    INSERT INTO INF_B_DA_MNTH_MCO_ACO_BASE_purge SELECT * FROM INF_B_DA_MNTH_MCO_ACO_BASE WHERE RUN_DATE > v_DTL_PURGE_DATE;
    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_BASE REUSE STORAGE';
    INSERT INTO INF_B_DA_MNTH_MCO_ACO_BASE SELECT * FROM INF_B_DA_MNTH_MCO_ACO_BASE_purge;
    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_BASE_purge';

--    DELETE FROM INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE WHERE RUN_DATE < v_DTL_PURGE_DATE;

    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE_purge';
    INSERT INTO INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE_purge SELECT * FROM INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE WHERE RUN_DATE > v_DTL_PURGE_DATE;
    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE REUSE STORAGE';
    INSERT INTO INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE SELECT * FROM INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE_purge;
    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_REVCDE_BASE_purge';

    COMMIT;

END;
/