SET pause OFF
SET feedback ON
SET TIME ON
SET timing ON


WHENEVER SQLERROR EXIT failure ROLLBACK

DECLARE
    v_DA_PURGE_AGG     NUMBER(3);
    v_DA_PURGE_DTL     NUMBER(3);
    v_DA_RUN_DATE      DATE;
    v_PARENT_BATCH_SEQ NUMBER(10);
    v_CHILD_BATCH_SEQ  NUMBER(10);
    v_AGG_PURGE_DATE   DATE;
    v_DTL_PURGE_DATE   DATE;
    v_DTL_PURGE_MNTH   VARCHAR2(9);
    v_NOOP             NUMBER(10); 
    v_DA_DAY_OFFSET    NUMBER(10);
    v_DTL_PURGE_WEEK   VARCHAR2(11);

BEGIN
-- Can run monthly or weekly detail purge - comment out as needed

--  Subtract one month because we will be adding the latest month later 
--  don't subtract for partitions
    SELECT - (TO_NUMBER(PARAM_VALUE, '999') - 1) INTO v_DA_PURGE_AGG     FROM INF_B_DQ_PARAMS WHERE PARAM_NAME = 'DA_PURGE_AGG';
--  Use - 0 for partitions -1 for move and truncate
    SELECT - (TO_NUMBER(PARAM_VALUE, '999') - 0) INTO v_DA_PURGE_DTL     FROM INF_B_DQ_PARAMS WHERE PARAM_NAME = 'DA_PURGE_DTL';
--  SELECT - (TO_NUMBER(PARAM_VALUE, '999') - 1) INTO v_DA_PURGE_DTL     FROM INF_B_DQ_PARAMS WHERE PARAM_NAME = 'DA_PURGE_DTL';
    SELECT TO_DATE(PARAM_VALUE,'YYYYMMDD')       INTO v_DA_RUN_DATE      FROM INF_B_DQ_PARAMS WHERE PARAM_NAME = 'DA_RUN_DATE';
    SELECT TO_NUMBER(PARAM_VALUE, '999999')      INTO v_PARENT_BATCH_SEQ FROM INF_B_DQ_PARAMS WHERE PARAM_NAME = 'DA_BATCH_SEQ';

    SELECT ADD_MONTHS(TRUNC(v_DA_RUN_DATE,'MONTH'),v_DA_PURGE_AGG) INTO v_AGG_PURGE_DATE FROM DUAL;
    SELECT ADD_MONTHS(TRUNC(v_DA_RUN_DATE,'MONTH'),v_DA_PURGE_DTL) INTO v_DTL_PURGE_DATE FROM DUAL;
    SELECT 'DA_' || TO_CHAR(v_DTL_PURGE_DATE,'YYYYMM') INTO v_DTL_PURGE_MNTH FROM DUAL;

-- Weekly
-- Offset to Monday - based on running on a different day of the week i.e. Wednesday or Thursday
-- Thursday = -3
    v_DA_DAY_OFFSET := -3;

-- +1 week due to partition looking back a week 
    SELECT v_DA_RUN_DATE + v_DA_DAY_OFFSET + ((v_DA_PURGE_DTL +1) * 7) INTO v_DTL_PURGE_DATE FROM DUAL;
    SELECT 'DA_' || TO_CHAR(v_DTL_PURGE_DATE,'YYYYMMDD') INTO v_DTL_PURGE_WEEK FROM DUAL;

    --DBMS_OUTPUT.PUT_LINE('v_AGG_PURGE_DATE ' || to_char(v_AGG_PURGE_DATE,'YYYYMMDD'));
    --DBMS_OUTPUT.PUT_LINE('v_DTL_PURGE_DATE ' || to_char(v_DTL_PURGE_DATE,'YYYYMMDD'));

    --Put an entry in INF_B_DQ_LOAD_BATCH so the main script can wait for this script to finish

    INSERT INTO INF_B_DQ_LOAD_BATCH
    (
        RUN_DATE,
        STEP_NUM,
        PROJECT_NAME,
        PROGRAM_NAME,
        PARENT_BATCH_SEQ,
        BATCH_START_DT_TM,
        STATUS
    )
    VALUES
    (
        v_DA_RUN_DATE,
        7,
        'DA',
        'PURGE_TABLES',
        v_PARENT_BATCH_SEQ,
        SYSDATE,
        'Running'
    )
    RETURNING DQ_BATCH_SEQ INTO v_CHILD_BATCH_SEQ;


    DELETE FROM INF_B_DA_MNTH_MCO_CLMTYP_ALERT WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_MCO_ACO_CLMTYP_ALERT WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_CLMNUM_MCO_CLMTYP_ALERT WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_CLMNUM_MCO_ACO_CLMTYP_ALERT WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_UTIL_MEM_MCO_CLMTYP_ALERT WHERE RUN_DATE < v_AGG_PURGE_DATE;
    DELETE FROM INF_B_DA_MNTH_UTIL_MEM_MCO_ACO_CLMTYP_ALERT WHERE RUN_DATE < v_AGG_PURGE_DATE;

-- I am using truncate copies - it is cleaner, but more dangerous
--    DELETE FROM INF_B_DA_MNTH_MCO_ACO_BASE WHERE RUN_DATE < v_DTL_PURGE_DATE;

-- Round two using move records
--    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_BASE_ALERT_PURGE';
--    INSERT INTO INF_B_DA_MNTH_MCO_ACO_BASE_ALERT_PURGE SELECT * FROM INF_B_DA_MNTH_MCO_ACO_BASE_ALERT WHERE RUN_DATE > v_DTL_PURGE_DATE;
--
--    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_BASE_ALERT REUSE STORAGE';
--    INSERT INTO INF_B_DA_MNTH_MCO_ACO_BASE_ALERT SELECT * FROM INF_B_DA_MNTH_MCO_ACO_BASE_ALERT_PURGE;
--    EXECUTE IMMEDIATE 'TRUNCATE TABLE INF_B_DA_MNTH_MCO_ACO_BASE_ALERT_PURGE';


-- Round three using partitions vs move records and rebuilded global indexes
  BEGIN
-- Monthly
    EXECUTE IMMEDIATE 'ALTER TABLE INF_B_DA_MNTH_MCO_ACO_BASE_ALERT DROP PARTITION ' || v_DTL_PURGE_MNTH;
-- Weekly
--    EXECUTE IMMEDIATE 'ALTER TABLE INF_B_DA_MNTH_MCO_ACO_BASE_ALERT DROP PARTITION ' || v_DTL_PURGE_WEEK;

    EXECUTE IMMEDIATE 'ALTER INDEX IX01_INF_B_DA_MNTH_MCO_ACO_BASE_ALERT REBUILD';
    EXECUTE IMMEDIATE 'ALTER INDEX IX02_INF_B_DA_MNTH_MCO_ACO_BASE_ALERT REBUILD';
  EXCEPTION
    WHEN OTHERS THEN 
        v_NOOP := 0;
-- Ignore errors with purge in case partition is already dropped
  END;

    UPDATE INF_B_DQ_LOAD_BATCH
    SET BATCH_END_DT_TM = SYSDATE,
    STATUS              = 'Complete'
    WHERE DQ_BATCH_SEQ  = v_CHILD_BATCH_SEQ;

    COMMIT;

END;
/

